/*2. Aggregation
How many class hours of each type did the program 233 got in year 2004/2005?*/


SELECT  XTIPOSAULA.TIPO,SUM(XTIPOSAULA.HORAS_TURNO*XTIPOSAULA.TURNOS) AS TOTAL_HOURS
FROM XTIPOSAULA INNER JOIN Y_XUCS ON XTIPOSAULA.CODIGO=XUCS.CODIGO
WHERE XTIPOSAULA.ANO_LETIVO='2004/2005' AND XUCS.CURSO='233'
GROUP BY XTIPOSAULA.TIPO;

SELECT  X_XTIPOSAULA.TIPO,SUM(X_XTIPOSAULA.HORAS_TURNO*X_XTIPOSAULA.TURNOS) AS TOTAL_HOURS
FROM X_XTIPOSAULA INNER JOIN X_XUCS ON X_XTIPOSAULA.CODIGO=X_XUCS.CODIGO
WHERE X_XTIPOSAULA.ANO_LETIVO='2004/2005' AND X_XUCS.CURSO='233'
GROUP BY X_XTIPOSAULA.TIPO;

SELECT  Y_XTIPOSAULA.TIPO,SUM(Y_XTIPOSAULA.HORAS_TURNO*Y_XTIPOSAULA.TURNOS) AS TOTAL_HOURS
FROM Y_XTIPOSAULA INNER JOIN Y_XUCS ON Y_XTIPOSAULA.CODIGO=Y_XUCS.CODIGO
WHERE Y_XTIPOSAULA.ANO_LETIVO='2004/2005' AND Y_XUCS.CURSO='233'
GROUP BY Y_XTIPOSAULA.TIPO;

SELECT  Z_XTIPOSAULA.TIPO,SUM(Z_XTIPOSAULA.HORAS_TURNO*Z_XTIPOSAULA.TURNOS)  AS TOTAL_HOURS
FROM Z_XTIPOSAULA INNER JOIN Z_XUCS ON Z_XTIPOSAULA.CODIGO=Z_XUCS.CODIGO
WHERE Z_XTIPOSAULA.ANO_LETIVO='2004/2005' AND Z_XUCS.CURSO='233'
GROUP BY Z_XTIPOSAULA.TIPO;
